Initial support for i18n
Re-Volt-America/RVA pull request #54
Opened 2024-01-30 19:36 UTC by nickskyline

2024-01-30 19:43 UTC, BGMP commented on app/views/application/_nav.haml
This needs to be updated to the latest navigation bar.

ref: https://github.com/Re-Volt-America/RVA/blob/master/app/views/application/_nav.haml

2024-01-30 19:47 UTC, BGMP requested changes
Nice job! Take a look at the comments I left. We need those resolved before I can review further.

2024-01-30 19:47 UTC, BGMP commented on app/views/application/_nav.haml
This needs to be updated to the latest navigation bar.

ref: https://github.com/Re-Volt-America/RVA/blob/master/app/views/application/_nav.haml

2024-01-30 19:47 UTC, BGMP commented on app/views/application/index.haml
> +              = t("application.index.recent.hosted-by", host: session.host) #{session.host}
Missing a line break here

2024-01-30 19:47 UTC, BGMP commented on app/views/sessions/extra.haml
What is this file?

2024-01-30 22:02 UTC, nickskyline commented on app/views/sessions/extra.haml
It was for testing purposes, I forgot to delete it

2024-01-30 22:47 UTC, BGMP commented
You may request my review when you finish off the changes. Same goes for https://github.com/Re-Volt-America/RVA/pull/53

Thanks, Nick!

2024-02-02 13:59 UTC, BGMP commented on app/views/sessions/extra.haml
Alright, I was so confused lol

2024-02-28 04:50 UTC, BGMP commented
I think this is good enough to merge. The language selector is available at the user settings, it has its own tab. Although, I've been thinking that maybe bringing back the on-screen flag icon to change locales would be a good idea.

Could you try the changes out on your end @nickskyline ?

2024-02-28 14:24 UTC, nickskyline commented
Looks and works good for me although it's a little weird to me that you have to introduce your password to only change the language.

And yes, bringing back that selector is great, specially for unregistered users.

2024-02-28 14:25 UTC, BGMP commented
> Looks and works good for me although it's a little weird to me that you have to introduce your password to only change the language.
> 
> And yes, bringing back that selector is great, specially for unregistered users. @BGMP

The issue with unregistered users is keeping track of their locale. I'm not sure if rails-i18n supports local storage or a solution similar to that...

2024-02-29 04:40 UTC, BGMP commented
Alright, I've brought back the language selector with the country flags and everything! We should be good to go now! 😄

2024-02-29 04:47 UTC, merged