Add metadata translation keys
Re-Volt-America/RVA pull request #77
Opened 2024-03-22 16:47 UTC by nickskyline

2024-03-28 03:11 UTC, BGMP requested changes
Nice job! It looks good as a starting point.

I realised we may have a singular/plural issue with car classes in spanish. For example, the page title "Re-Volt America - Rookie Cars" translates to "Re-Volt America - Autos Novato"; or even worse, "Re-Volt America - Advanced Cars" to "Re-Volt America - Autos Avanzado". 

The capitalisation of the strings is also being assumed incorrectly by passing the classes as variables. See the fragment below:

https://github.com/Re-Volt-America/RVA/pull/77/files#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd7b4cd7R368-R371

I'd say just create a string for each car class by separate, under the same key you've added this one, and avoid passing car classes as variables to prevent all of the issues listed above.

2024-03-31 14:22 UTC, BGMP requested changes
I think something went wrong whilst you were rebasing your progress. Make sure to keep the changes which had been made during the last several days.

Some typos were introduced back because of this bad rebase :(.

My advice would be to revert, rebase on top of master and go with the middle option between keeping your changes only and theirs only; that option will let you cherry-pick what you want to accept and what you want to keep from your changes alone.

2024-03-31 14:22 UTC, BGMP commented on config/locales/en.yml
> +      mod: "Mod"
Should be "Moderator", not "Mod"

```suggestion
      mod: "Moderator"
```

2024-03-31 14:22 UTC, BGMP commented on config/locales/en.yml
> +      no-team-results: "No team results to disiplay"
Typo
```suggestion
      no-team-results: "No team results to display"
```

2024-03-31 14:22 UTC, BGMP commented on config/locales/en.yml
> +          li-2-html: "Copy and paste inside the app this command; <code> am start -n com.rvgl.rvgl/.RVGLActivity -e args \"-lobby &lt;ip&gt  -pass &lt;password&gt </code> you ought write the IP and p
This was reverted for some reason? Why?

2024-03-31 14:22 UTC, BGMP commented on config/locales/en.yml
> -      faq: "Frequently Asked Questions"
Removed this for no reason?

2024-03-31 15:02 UTC, nickskyline commented
Apologies, it was a local file issue :(

It should be fine now.

2024-04-05 14:56 UTC, BGMP commented
Thanks for taking care of it. I think it should be good to go now !

2024-04-05 14:56 UTC, merged